#!/usr/bin/env bash
# Generate the Ed25519 model-signing keypair. The PRIVATE key stays ONLY on the
# Pi (this host). Outputs:
#   $KEY_DIR/model_ed25519.pem       (private, chmod 600 - never leaves the Pi)
#   $KEY_DIR/model_ed25519_pub.pem   (public, used by the API to verify uploads)
#   $OUT_HEADER                      (C header with the raw 32-byte pubkey for FW)
#   $KEY_DIR/model_ed25519.pem.gpg   (optional GPG-encrypted escrow backup)
#
# Usage: ./scripts/gen_model_key.sh [KEY_DIR] [OUT_HEADER] [GPG_RECIPIENT]
set -euo pipefail

KEY_DIR="${1:-/data/keys}"
OUT_HEADER="${2:-../../include/glucose_model_pubkey.h}"
GPG_RECIPIENT="${3:-}"

mkdir -p "$KEY_DIR"
PRIV="$KEY_DIR/model_ed25519.pem"
PUB="$KEY_DIR/model_ed25519_pub.pem"

if [ -f "$PRIV" ]; then
    echo "Private key already exists at $PRIV — refusing to overwrite."
    exit 1
fi

echo "Generating Ed25519 keypair..."
openssl genpkey -algorithm ed25519 -out "$PRIV"
chmod 600 "$PRIV"
openssl pkey -in "$PRIV" -pubout -out "$PUB"

# Extract the raw 32-byte public key (last 32 bytes of the DER SubjectPublicKeyInfo).
RAW_HEX=$(openssl pkey -in "$PUB" -pubin -outform DER | tail -c 32 | xxd -p -c 32)

echo "Writing firmware public-key header to $OUT_HEADER"
{
  echo "/* Auto-generated by apps/server/scripts/gen_model_key.sh. DO NOT EDIT. */"
  echo "#ifndef GLUCOSE_MODEL_PUBKEY_H"
  echo "#define GLUCOSE_MODEL_PUBKEY_H"
  echo "#include <stdint.h>"
  echo "static const uint8_t GLUCOSE_MODEL_PUBKEY[32] = {"
  echo "$RAW_HEX" | sed 's/\(..\)/0x\1, /g' | fold -s -w 60 | sed 's/^/\t/'
  echo "};"
  echo "#endif /* GLUCOSE_MODEL_PUBKEY_H */"
} > "$OUT_HEADER"

if [ -n "$GPG_RECIPIENT" ]; then
    echo "Creating GPG-encrypted escrow backup for $GPG_RECIPIENT"
    gpg --yes --output "$PRIV.gpg" --encrypt --recipient "$GPG_RECIPIENT" "$PRIV"
fi

echo "Done. Public key: $PUB"
echo "Set CONFIG_GLUCOSE_MODEL_SIGNED=y and rebuild firmware to enforce signatures."
