# =============================================================================
# Full Flash Erase and Program Script
# =============================================================================
# This script:
# 1. Erases all internal flash
# 2. Programs merged.hex (MCUboot + signed app)
# 3. Verifies the image header is present at 0xA000
# 4. Resets the device to boot
#
# Usage: .\flash_full.ps1
# =============================================================================

param(
    [switch]$SkipVerify,
    [switch]$Verbose
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Full Flash Erase and Program Script" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

$WorkspaceDir = Split-Path -Parent $PSScriptRoot
function Get-BuildDirName {
    $projectRoot = (Get-Item $PSScriptRoot).Parent.Parent.FullName
    $configFile = Join-Path $projectRoot "scripts\setup\nrf_sdk_config.json"
    if (Test-Path $configFile) {
        try {
            $cfg = Get-Content $configFile -Raw | ConvertFrom-Json
            if ($cfg.BuildDirName) { return $cfg.BuildDirName }
        } catch {}
    }
    return "build_sdk_v330"
}

$ProjectRoot = (Get-Item $PSScriptRoot).Parent.Parent.FullName
$BuildDirName = Get-BuildDirName
$BuildDir = Join-Path $ProjectRoot $BuildDirName
$MergedCandidates = @()
$MergedCandidates += @(Get-ChildItem -Path $BuildDir -Filter "merged_*.hex" -File -ErrorAction SilentlyContinue |
    Sort-Object Name |
    ForEach-Object { $_.FullName })
$MergedCandidates += Join-Path $BuildDir "merged.hex"
$MergedHex = $null
foreach ($candidate in $MergedCandidates) {
    if (Test-Path $candidate) {
        $MergedHex = $candidate
        break
    }
}
if (-not $MergedHex) {
    $MergedHex = Join-Path $BuildDir "merged.hex"
}
$JLinkExe = "C:\Program Files\SEGGER\JLink\JLink.exe"

# Verify files exist
if (-not (Test-Path $MergedHex)) {
    Write-Host "[ERROR] merged image not found at: $MergedHex" -ForegroundColor Red
    Write-Host "        Searched: $BuildDir\merged_*.hex" -ForegroundColor Yellow
    Write-Host "        Searched: $BuildDir\merged.hex" -ForegroundColor Yellow
    Write-Host "        Please build the project first with: .\\scripts\\setup\\build_project.ps1" -ForegroundColor Yellow
    exit 1
}

if (-not (Test-Path $JLinkExe)) {
    Write-Host "[ERROR] JLink.exe not found at: $JLinkExe" -ForegroundColor Red
    exit 1
}

# Verify merged.hex contains the image header
Write-Host "Verifying merged.hex contains MCUboot image header..." -ForegroundColor Yellow
$headerLine = Select-String -Path $MergedHex -Pattern ":10A000003DB8F396" | Select-Object -First 1
if (-not $headerLine) {
    Write-Host "[ERROR] merged.hex does not contain MCUboot image header at 0xA000!" -ForegroundColor Red
    Write-Host "        The app may not be properly signed." -ForegroundColor Yellow
    exit 1
}
Write-Host "[OK] Image header found in merged.hex" -ForegroundColor Green

# Create JLink command file
$jlinkCommands = @"
// Full Flash Erase and Program
// Generated by flash_full.ps1

// Connect
connect

// Halt the CPU
halt

// Erase all internal flash
erase

// Program merged.hex
loadfile "$($MergedHex.Replace('\', '/'))"

// Verify (optional but recommended)
verifybin "$($MergedHex.Replace('\', '/').Replace('.hex', '.bin'))" 0x0

// Read back image header to verify
mem32 0xA000 4

// Reset and run
r
g

exit
"@

$jlinkFile = "$env:TEMP\flash_full.jlink"
$jlinkCommands | Out-File -FilePath $jlinkFile -Encoding ASCII

Write-Host ""
Write-Host "Step 1: Erasing and programming flash..." -ForegroundColor Yellow
Write-Host "        Using: $MergedHex" -ForegroundColor Gray

# Run JLink
$process = Start-Process -FilePath $JLinkExe `
    -ArgumentList @(
        "-device", "nRF52840_xxAA",
        "-if", "swd",
        "-speed", "4000",
        "-autoconnect", "1",
        "-CommandFile", $jlinkFile
    ) `
    -NoNewWindow -Wait -PassThru

if ($process.ExitCode -ne 0) {
    Write-Host "[ERROR] JLink programming failed with exit code: $($process.ExitCode)" -ForegroundColor Red
    exit 1
}

Write-Host "[OK] Programming complete" -ForegroundColor Green

# Verify the header was written
if (-not $SkipVerify) {
    Write-Host ""
    Write-Host "Step 2: Verifying image header at 0xA000..." -ForegroundColor Yellow
    
    $verifyCommands = @"
connect
halt
mem32 0xA000 4
exit
"@
    $verifyFile = "$env:TEMP\verify_header.jlink"
    $verifyCommands | Out-File -FilePath $verifyFile -Encoding ASCII
    
    $output = & $JLinkExe -device nRF52840_xxAA -if swd -speed 4000 -autoconnect 1 -CommandFile $verifyFile 2>&1
    
    if ($output -match "0000A000\s*=\s*96F3B83D") {
        Write-Host "[OK] Image header verified: 0x96F3B83D (MCUboot magic)" -ForegroundColor Green
    } elseif ($output -match "0000A000\s*=\s*FFFFFFFF") {
        Write-Host "[ERROR] Image header NOT written! Flash shows 0xFFFFFFFF" -ForegroundColor Red
        Write-Host "        The programming may have failed." -ForegroundColor Yellow
        exit 1
    } else {
        Write-Host "[WARNING] Could not verify image header" -ForegroundColor Yellow
        if ($Verbose) {
            Write-Host "JLink output:" -ForegroundColor Gray
            $output | ForEach-Object { Write-Host "  $_" }
        }
    }
    
    Remove-Item $verifyFile -ErrorAction SilentlyContinue
}

# Reset and run
Write-Host ""
Write-Host "Step 3: Resetting device to boot..." -ForegroundColor Yellow

$resetCommands = @"
connect
r
g
exit
"@
$resetFile = "$env:TEMP\reset_device.jlink"
$resetCommands | Out-File -FilePath $resetFile -Encoding ASCII

& $JLinkExe -device nRF52840_xxAA -if swd -speed 4000 -autoconnect 1 -CommandFile $resetFile 2>&1 | Out-Null

Remove-Item $resetFile -ErrorAction SilentlyContinue
Remove-Item $jlinkFile -ErrorAction SilentlyContinue

Write-Host "[OK] Device reset" -ForegroundColor Green

Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "  Flash Complete!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "The device should now boot:" -ForegroundColor White
Write-Host "  1. MCUboot starts at 0x0" -ForegroundColor Gray
Write-Host "  2. MCUboot reads image header at 0xA000" -ForegroundColor Gray
Write-Host "  3. MCUboot validates signature" -ForegroundColor Gray  
Write-Host "  4. MCUboot jumps to app at 0xA200" -ForegroundColor Gray
Write-Host ""
Write-Host "Use RTT Viewer or Ozone Terminal to see boot messages." -ForegroundColor Cyan

