#!/usr/bin/env python3
"""Download Nordic bluetooth-numbers-database v1 JSON and emit Dart SIG UUID lookup."""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

BASE = "https://raw.githubusercontent.com/nordicsemi/bluetooth-numbers-database/master/v1"
FILES = (
    "service_uuids.json",
    "characteristic_uuids.json",
    "descriptor_uuids.json",
)
SIG_BASE = "0000{:04x}-0000-1000-8000-00805f9b34fb"
OUT = Path(__file__).resolve().parents[2] / "apps" / "mobile" / "lib" / "protocol" / "generated" / "sig_uuids.g.dart"


def expand_uuid(uuid16: int) -> str:
    return SIG_BASE.format(uuid16 & 0xFFFF).lower()


def main() -> int:
    merged: dict[str, str] = {}
    for name in FILES:
        url = f"{BASE}/{name}"
        print(f"Fetching {url}")
        with urllib.request.urlopen(url, timeout=60) as resp:
            data = json.load(resp)
        for entry in data:
            uid = entry.get("uuid")
            label = entry.get("name") or entry.get("description")
            if uid is None or not label:
                continue
            if isinstance(uid, str):
                merged[uid.lower()] = str(label)
            elif isinstance(uid, int):
                merged[expand_uuid(uid)] = str(label)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// GENERATED by scripts/tools/sync_bluetooth_uuids.py — do not edit.",
        "",
        "const Map<String, String> sigUuidNames = {",
    ]
    for uuid, label in sorted(merged.items()):
        safe = label.replace("'", "\\'")
        lines.append(f"  '{uuid}': '{safe}',")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(merged)} entries to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
