/* ble_gatt_security.h - GATT permission macros per BLE security profile
 *
 * OPEN profile: legacy permissive layout (development).
 * SECURE profile: targets in docs/ble/BLE_DATA_SECURITY_DATABASE.md
 */

#ifndef BLE_GATT_SECURITY_H
#define BLE_GATT_SECURITY_H

#include <zephyr/bluetooth/gatt.h>

/* Base permission groups */
#define BLE_GATT_PERM_RW_OPEN  (BT_GATT_PERM_READ | BT_GATT_PERM_WRITE)
#define BLE_GATT_PERM_W_OPEN   BT_GATT_PERM_WRITE
#define BLE_GATT_PERM_R_OPEN   BT_GATT_PERM_READ
#define BLE_GATT_PERM_CCC_OPEN (BT_GATT_PERM_READ | BT_GATT_PERM_WRITE)

#define BLE_GATT_PERM_RW_ENC   (BT_GATT_PERM_READ_ENCRYPT | BT_GATT_PERM_WRITE_ENCRYPT)
#define BLE_GATT_PERM_W_ENC    BT_GATT_PERM_WRITE_ENCRYPT
#define BLE_GATT_PERM_R_ENC    BT_GATT_PERM_READ_ENCRYPT
#define BLE_GATT_PERM_CCC_ENC  (BT_GATT_PERM_READ_ENCRYPT | BT_GATT_PERM_WRITE_ENCRYPT)

#define BLE_GATT_PERM_RW_AUTH  (BT_GATT_PERM_READ_AUTHEN | BT_GATT_PERM_WRITE_AUTHEN)
#define BLE_GATT_PERM_W_AUTH   BT_GATT_PERM_WRITE_AUTHEN
#define BLE_GATT_PERM_R_AUTH   BT_GATT_PERM_READ_AUTHEN
#define BLE_GATT_PERM_CCC_AUTH (BT_GATT_PERM_READ_AUTHEN | BT_GATT_PERM_WRITE_AUTHEN)

#if defined(CONFIG_BLE_SECURITY_PROFILE_SECURE)

/* Wearable config */
#define BLE_PERM_DEVICE_NAME    BLE_GATT_PERM_RW_ENC
#define BLE_PERM_RTC_TRIM       BLE_GATT_PERM_RW_ENC
#define BLE_PERM_BATTERY_LOW    BLE_GATT_PERM_RW_ENC
#define BLE_PERM_BRIGHTNESS     BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_VOLUME         BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_PPG_PREF       BLE_GATT_PERM_RW_ENC
#define BLE_PERM_MEAS_CTRL      BLE_GATT_PERM_W_ENC
#define BLE_PERM_PPG_DECIMATE   BLE_GATT_PERM_RW_ENC
#define BLE_PERM_SAMPLING_CFG   BLE_GATT_PERM_RW_ENC
#define BLE_PERM_PMIC_CTRL      BLE_GATT_PERM_W_AUTH
#define BLE_PERM_ADMIN_CTRL     BLE_GATT_PERM_W_AUTH

/* Sensor notify CCC */
#define BLE_PERM_CCC_PMIC       BLE_GATT_PERM_CCC_ENC
#define BLE_PERM_CCC_TEMP       BLE_GATT_PERM_CCC_ENC
#define BLE_PERM_CCC_PMIC_EXT   BLE_GATT_PERM_CCC_ENC
#define BLE_PERM_CCC_PROXIMITY  BLE_GATT_PERM_CCC_ENC
#define BLE_PERM_CCC_ACCEL      BLE_GATT_PERM_CCC_ENC
#define BLE_PERM_CCC_VITALS     BLE_GATT_PERM_CCC_AUTH
#define BLE_PERM_CCC_GLUCOSE    BLE_GATT_PERM_CCC_AUTH
#define BLE_PERM_CCC_GLUC_SAMP  BLE_GATT_PERM_CCC_AUTH
#define BLE_PERM_CCC_GLUC_ALGO  BLE_GATT_PERM_CCC_AUTH
#define BLE_PERM_CCC_PPG        BLE_GATT_PERM_CCC_AUTH
#define BLE_PERM_CCC_SENSOR_ALL BLE_GATT_PERM_CCC_AUTH
#define BLE_PERM_CCC_MEAS_STAT  BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_PROXIMITY_READ BLE_GATT_PERM_R_ENC

/* WiFi config */
#define BLE_PERM_WIFI_ENABLE    BLE_GATT_PERM_RW_ENC
#define BLE_PERM_WIFI_SSID      BLE_GATT_PERM_RW_AUTH
#define BLE_PERM_WIFI_PASSWORD  BLE_GATT_PERM_W_AUTH
#define BLE_PERM_WIFI_STATUS_R  BLE_GATT_PERM_R_ENC
#define BLE_PERM_WIFI_STATUS_CCC BLE_GATT_PERM_CCC_ENC
#define BLE_PERM_WIFI_CONNECT   BLE_GATT_PERM_W_ENC
#define BLE_PERM_WIFI_SESSION_CTRL BLE_GATT_PERM_W_AUTH
#define BLE_PERM_WIFI_SESSION_STATUS_R BLE_GATT_PERM_R_ENC
#define BLE_PERM_WIFI_SESSION_STATUS_CCC BLE_GATT_PERM_CCC_ENC

#else /* CONFIG_BLE_SECURITY_PROFILE_OPEN (default dev) */

#define BLE_PERM_DEVICE_NAME    BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_RTC_TRIM       BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_BATTERY_LOW    BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_BRIGHTNESS     BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_VOLUME         BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_PPG_PREF       BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_MEAS_CTRL      BLE_GATT_PERM_W_OPEN
#define BLE_PERM_PPG_DECIMATE   BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_SAMPLING_CFG   BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_PMIC_CTRL      BLE_GATT_PERM_W_ENC
#define BLE_PERM_ADMIN_CTRL     BLE_GATT_PERM_W_ENC

#define BLE_PERM_CCC_PMIC       BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_TEMP       BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_PMIC_EXT   BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_PROXIMITY  BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_ACCEL      BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_VITALS     BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_GLUCOSE    BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_GLUC_SAMP  BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_GLUC_ALGO  BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_PPG        BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_SENSOR_ALL BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_CCC_MEAS_STAT  BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_PROXIMITY_READ BLE_GATT_PERM_R_OPEN

#define BLE_PERM_WIFI_ENABLE    BLE_GATT_PERM_RW_OPEN
#define BLE_PERM_WIFI_SSID      BLE_GATT_PERM_RW_ENC
#define BLE_PERM_WIFI_PASSWORD  BLE_GATT_PERM_W_ENC
#define BLE_PERM_WIFI_STATUS_R  BLE_GATT_PERM_R_OPEN
#define BLE_PERM_WIFI_STATUS_CCC BLE_GATT_PERM_CCC_OPEN
#define BLE_PERM_WIFI_CONNECT   BLE_GATT_PERM_W_OPEN
#define BLE_PERM_WIFI_SESSION_CTRL BLE_GATT_PERM_W_ENC
#define BLE_PERM_WIFI_SESSION_STATUS_R BLE_GATT_PERM_R_OPEN
#define BLE_PERM_WIFI_SESSION_STATUS_CCC BLE_GATT_PERM_CCC_OPEN

#endif /* CONFIG_BLE_SECURITY_PROFILE_SECURE */

#endif /* BLE_GATT_SECURITY_H */
